## I. Input Data

In [3]:
pwd

'/Users/xulin/2018_project_autumn/aml_task2/input/code'

In [4]:
import numpy as np
import pandas as pd
import os
trainx = pd.read_csv('../original_data/task2/X_train.csv')
trainy = pd.read_csv('../original_data/task2/y_train.csv')
testx  = pd.read_csv('../original_data/task2/X_test.csv')

In [5]:
xdropid=trainx.drop('id', axis=1)
ydropid= trainy.y
testx_noid= testx.drop('id', axis=1)
print(xdropid.shape,ydropid.shape,testx_noid.shape)

(4800, 1000) (4800,) (4100, 1000)


In [6]:
print(trainx.head())
# no missing value
trainx.isnull().sum()
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import RobustScaler

scaler = RobustScaler()
print(scaler.fit(xdropid))

x_scale= pd.DataFrame(scaler.transform(xdropid))
print(x_scale.head())
testx_scale=pd.DataFrame(scaler.transform(testx_noid))
from sklearn.ensemble import IsolationForest
import matplotlib.pyplot as plt

rng = np.random.RandomState(42)

clf = IsolationForest(behaviour='new',random_state=rng, contamination=0.1)
clf.fit(x_scale)
x_clf = clf.predict(x_scale)
testx_clf= clf.predict(testx_scale)
print((x_clf<0).sum())
print((testx_clf<0).sum())
x_clf=pd.DataFrame(x_clf)
x_add=pd.DataFrame(np.concatenate((x_scale, x_clf), axis=1))
print(x_add.shape)

testx_clf=pd.DataFrame(testx_clf)
testx_add=pd.DataFrame(np.concatenate((testx_scale, testx_clf), axis=1))
print(testx_add.shape)

   id        x0        x1        x2        x3        x4        x5        x6  \
0   0 -4.524480 -0.718917  0.827537 -2.336564  1.905992 -1.424985 -5.622933   
1   1 -0.561814 -0.115757 -0.113303 -0.322508 -0.080855  0.042634 -0.319990   
2   2 -0.547026 -0.045593  1.016072 -0.068002 -0.670472 -0.551299 -0.550926   
3   3 -1.939258 -0.284554  1.276007 -0.500731  1.088817 -0.897736 -1.530660   
4   4 -0.386835 -0.143997  0.506509 -0.648928 -0.614121  0.211504  0.025600   

         x7        x8    ...         x990      x991      x992      x993  \
0 -0.739429  0.334367    ...    -3.214350 -4.083583 -1.240234  1.581522   
1 -0.066997  0.281196    ...    -0.262083 -0.437542  0.300902  0.502415   
2  0.393147  1.022467    ...     0.064608 -0.361322 -0.440028  0.278972   
3 -0.952914  1.157809    ...    -2.341105 -1.663250 -1.224091  0.617387   
4 -0.272372 -0.215564    ...     0.083148  0.568495  0.050980  0.317415   

       x994      x995      x996      x997      x998      x999  
0 -3.14744

In [7]:
# The method we want to use svm : one vs one, one vs all, confusion metrics
# notice: imbalance class

ydropid.value_counts()

1.0    3600
2.0     600
0.0     600
Name: y, dtype: int64

In [8]:
x_add.shape
y.shape

NameError: name 'y' is not defined

In [19]:
from sklearn.model_selection import KFold
from sklearn.metrics import balanced_accuracy_score
from sklearn.svm import LinearSVC
from sklearn import svm
kf = KFold(n_splits=5)
X,y= X_new,ydropid

for train_index, test_index in kf.split(X):
    clf = LinearSVC(random_state=0, tol=1e-5,multi_class='ovr',class_weight='balanced')
    x_train, x_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    clf.fit(x_train, y_train)
    BMAC = balanced_accuracy_score(y_test, clf.predict(x_test))
    print(BMAC)

/Users/xulin/anaconda3/lib/python3.6/site-packages/sklearn/svm/base.py:922: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


0.628042659903751


/Users/xulin/anaconda3/lib/python3.6/site-packages/sklearn/svm/base.py:922: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


0.6426443452880196


/Users/xulin/anaconda3/lib/python3.6/site-packages/sklearn/svm/base.py:922: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


0.5978210623027784


/Users/xulin/anaconda3/lib/python3.6/site-packages/sklearn/svm/base.py:922: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


0.6161815586766853
0.6435446425855259


/Users/xulin/anaconda3/lib/python3.6/site-packages/sklearn/svm/base.py:922: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


In [15]:
import numpy as np
from matplotlib.colors import ListedColormap
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import make_moons, make_circles, make_classification
from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.gaussian_process.kernels import RBF
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis

names = ["Nearest Neighbors", "Linear SVM", "RBF SVM", "Gaussian Process",
         "Decision Tree", "Random Forest", "Neural Net", "AdaBoost",
         "Naive Bayes", "QDA"]

classifiers = [
    KNeighborsClassifier(3),
    SVC(kernel="linear", C=0.025),
    SVC(gamma=2, C=1),
    GaussianProcessClassifier(1.0 * RBF(1.0)),
    DecisionTreeClassifier(max_depth=5),
    RandomForestClassifier(max_depth=5, n_estimators=10, max_features=1),
    MLPClassifier(alpha=1),
    AdaBoostClassifier(),
    GaussianNB(),
    QuadraticDiscriminantAnalysis()]

In [20]:
from sklearn.svm import SVC
from sklearn.multiclass import OneVsRestClassifier
ovr= OneVsRestClassifier(SVC(kernel='linear',class_weight='auto'))
print(cross_val_score(ovr, X, y,scoring='balanced_accuracy', cv=3))  

NameError: name 'cross_val_score' is not defined

In [14]:
X,y= xdropid,ydropid
from sklearn.metrics import balanced_accuracy_score
#BMAC = balanced_accuracy_score()
from sklearn.model_selection import cross_val_score
clf = svm.SVC(kernel='linear', C=1.0)
print(cross_val_score(clf, X, y,scoring='balanced_accuracy', cv=3))  

[0.59111111 0.60166667 0.59611111]


In [17]:
X,y= xdropid,ydropid


clf = svm.SVC(kernel='rbf', C=1.0)
print(cross_val_score(clf, X, y,scoring='balanced_accuracy', cv=3))  

/Users/xulin/anaconda3/lib/python3.6/site-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
/Users/xulin/anaconda3/lib/python3.6/site-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
/Users/xulin/anaconda3/lib/python3.6/site-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


[0.54611111 0.54       0.54055556]


In [21]:
clf = svm.SVC(kernel='linear', C=1.0, class_weight='balanced')
print(cross_val_score(clf, X, y,scoring='balanced_accuracy', cv=3)) 

[0.59111111 0.60194444 0.59611111]


In [46]:
for i in range(1,10):
    clf = svm.SVC(kernel='linear', C=i/10)
    print(cross_val_score(clf, X, y,scoring='balanced_accuracy', cv=3))   


[0.58583333 0.59305556 0.60638889]
[0.58583333 0.59305556 0.60638889]
[0.58583333 0.59305556 0.60638889]
[0.58583333 0.59305556 0.60638889]
[0.58583333 0.59305556 0.60638889]


KeyboardInterrupt: 

In [38]:
clf = svm.SVC(kernel='linear', C=0.1)
print(cross_val_score(clf, X, y,scoring='balanced_accuracy', cv=3))



[0.58583333 0.59305556 0.60638889]


In [49]:
clf = svm.SVC(kernel='linear', C=0.1, class_weight='balanced')
X,y= xdropid,ydropid

newy=clf.fit(X, y, sample_weight=y).predict(xdropid)
print(newy)

pd.DataFrame(newy)

output = pd.DataFrame({'y': newy})

output.index.names = ['id']

output.to_csv('../../output.csv')

In [50]:
print(newy)

pd.DataFrame(newy)

output = pd.DataFrame({'y': newy})

output.index.names = ['id']

output.to_csv('../../output.csv')

[0. 1. 0. ... 0. 1. 1.]


In [53]:
from sklearn.svm import LinearSVC
from sklearn.gaussian_process.kernels import RBF
clf = LinearSVC(random_state=0, tol=1e-5,multi_class='ovr',class_weight='balanced')
print(cross_val_score(clf, X, y,scoring='balanced_accuracy', cv=3)) 

/Users/xulin/anaconda3/lib/python3.6/site-packages/sklearn/svm/base.py:922: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
/Users/xulin/anaconda3/lib/python3.6/site-packages/sklearn/svm/base.py:922: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


[0.56861111 0.56111111 0.57055556]


/Users/xulin/anaconda3/lib/python3.6/site-packages/sklearn/svm/base.py:922: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


In [56]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif
skb= SelectKBest(f_classif, k=550)
skb.fit(x_add,ydropid)
X_new= skb.transform(x_add)
testx_new= skb.transform(testx_add)
print(X_new.shape)

(4800, 550)


In [44]:
from sklearn.svm import SVC
clf = SVC(C=1.0, cache_size=200, coef0=0.0,
    decision_function_shape='ovr', degree=5, gamma='auto', kernel='rbf',
    max_iter=-1, probability=False, random_state=0, shrinking=True,
    tol=1e-5, class_weight='balanced')
print(cross_val_score(clf, X_new, ydropid,scoring='balanced_accuracy', cv=5)) 

[0.68333333 0.68194444 0.6875     0.68935185 0.66388889]


In [57]:
from sklearn.svm import SVC
clf = SVC(C=1, cache_size=200, coef0=0.0,
    decision_function_shape='ovr', degree=5, gamma='auto', kernel='rbf',
    max_iter=-1, probability=False, random_state=0, shrinking=True,
    tol=1e-5, class_weight='balanced')
print(cross_val_score(clf, X_new, ydropid,scoring='balanced_accuracy', cv=5))

[0.6912037  0.69722222 0.71666667 0.69212963 0.67453704]


In [55]:
# clf = SVC(C=1.0, cache_size=200, coef0=0.0,
#     decision_function_shape='ovr', degree=5, gamma='auto', kernel='rbf',
#     max_iter=-1, probability=False, random_state=0, shrinking=True,
#     tol=1e-5, class_weight='balanced')
X,y= X_new,ydropid

newy=clf.fit(X_new, y).predict(testx_new)
print(newy)


output= pd.DataFrame({'id': testx.id, 'y': newy})
output.to_csv('../../output4.csv', index = False)

[0. 0. 1. ... 0. 1. 1.]


In [58]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif
skb= SelectKBest(f_classif, k='all')
skb.fit(x_add,ydropid)
X_new= skb.transform(x_add)
testx_new= skb.transform(testx_add)
print(X_new.shape)
from sklearn.svm import SVC
clf = SVC(C=1, cache_size=200, coef0=0.0,
    decision_function_shape='ovr', degree=5, gamma='auto', kernel='rbf',
    max_iter=-1, probability=False, random_state=0, shrinking=True,
    tol=1e-5, class_weight='balanced')
print(cross_val_score(clf, X_new, ydropid,scoring='balanced_accuracy', cv=5))

(4800, 1001)
[0.71435185 0.70833333 0.69861111 0.68842593 0.67314815]


In [62]:
clf = SVC(C=1, cache_size=200, coef0=0.0,
    decision_function_shape='ovr', degree=5, gamma='auto', kernel='rbf',
    max_iter=-1, probability=False, random_state=0, shrinking=True,
    tol=1e-5, class_weight='balanced')
newy=clf.fit(X_new, y).predict(testx_new)
print(newy)


output= pd.DataFrame({'id': testx.id, 'y': newy})
output.to_csv('../../output5.csv', index = False)

[0. 0. 1. ... 0. 1. 1.]


In [60]:
testx_new.shape

(4100, 1001)

In [37]:
clf = LinearSVC(random_state=0, tol=1e-5,multi_class='ovr',class_weight='balanced')
X,y= X_new,ydropid

newy=clf.fit(X, y, sample_weight=y).predict(testx_new)
print(newy)

pd.DataFrame(newy)

output5.to_csv('../../output3.csv', index = False)




[0. 0. 1. ... 1. 1. 1.]


/Users/xulin/anaconda3/lib/python3.6/site-packages/sklearn/svm/base.py:922: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


NameError: name 'cross_val_score' is not defined

In [27]:
from sklearn.model_selection import cross_val_score
clf = LinearSVC(random_state=0, tol=1e-5, multi_class='ovr', class_weight='balanced',max_iter=10000)
print(cross_val_score(clf, X_new, ydropid, scoring='balanced_accuracy', cv=5))



[0.62611111 0.60472222 0.63916667]


In [35]:
output= pd.DataFrame({'id': testx.id, 'y': newy})

In [36]:
output5.to_csv('../../output2.csv', index = False)